/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAFLI NUR FAUZI P
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        harga1 = new javax.swing.JTextField();
        harga2 = new javax.swing.JTextField();
        harga3 = new javax.swing.JTextField();
        ptnkeluar = new javax.swing.JButton();
        ptnproses = new javax.swing.JButton();
        ptnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        harga4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("diskon");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 220, 80, 14);
        getContentPane().add(diskon);
        diskon.setBounds(120, 210, 190, 30);
        getContentPane().add(harga1);
        harga1.setBounds(120, 50, 190, 30);
        getContentPane().add(harga2);
        harga2.setBounds(120, 90, 190, 30);
        getContentPane().add(harga3);
        harga3.setBounds(120, 130, 190, 30);

        ptnkeluar.setText("keluar");
        ptnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(ptnkeluar);
        ptnkeluar.setBounds(260, 250, 61, 23);

        ptnproses.setText("proses");
        ptnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnprosesActionPerformed(evt);
            }
        });
        getContentPane().add(ptnproses);
        ptnproses.setBounds(60, 250, 73, 23);

        ptnhapus.setText("hapus");
        ptnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(ptnhapus);
        ptnhapus.setBounds(160, 250, 61, 23);

        jLabel2.setText("pembayaran");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 10, 80, 14);

        jLabel3.setText("harga barang1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 80, 14);

        jLabel4.setText("harga barang2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 80, 14);

        jLabel5.setText("harga barang3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 80, 14);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 290, 240, 180);
        getContentPane().add(harga4);
        harga4.setBounds(120, 170, 190, 30);

        jLabel6.setText("harga barang4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 80, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ptnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnprosesActionPerformed
        String hargab1 = harga1.getText();
        String hargab2 = harga2.getText();
        String hargab3 = harga3.getText();
        String hargab4 = harga4.getText();
        String Diskon = diskon.getText();
        
        int hrg1 = Integer.parseInt(harga1.getText());
        int hrg2 = Integer.parseInt(harga2.getText());
        int hrg3 = Integer.parseInt(harga3.getText());
        int hrg4 = Integer.parseInt(harga4.getText());
        int dsk = Integer.parseInt(diskon.getText());
        
        int total_harga = hrg1 + hrg2 + hrg3 + hrg4;
        int diskon = total_harga * dsk / 100;
        int total_bayar = total_harga - diskon;
        
        hasil.setText("Harga barang 1   = "+hargab1+"\n"+
                      "Harga barang 2   = "+hargab2+"\n"+
                      "Harga barang 3   = "+hargab3+"\n"+
                      "Harga barang 4   = "+hargab4+"\n"+
                      "Diskon           = "+Diskon+"\n"+
                      "Total harga      = "+total_harga+"\n"+
                      "Total bayar      = "+total_bayar);
 // TODO add your handling code here:
    }//GEN-LAST:event_ptnprosesActionPerformed

    private void ptnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnhapusActionPerformed
harga1.setText("");
        harga2.setText("");
        harga3.setText("");
        harga4.setText("");
        diskon.setText("");
        hasil.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ptnhapusActionPerformed

    private void ptnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnkeluarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ptnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField harga1;
    private javax.swing.JTextField harga2;
    private javax.swing.JTextField harga3;
    private javax.swing.JTextField harga4;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ptnhapus;
    private javax.swing.JButton ptnkeluar;
    private javax.swing.JButton ptnproses;
    // End of variables declaration//GEN-END:variables
}
