/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAFLI NUR FAUZI P
 */
public class kusi1 extends javax.swing.JFrame {

    /**
     * Creates new form kusi1
     */
    public kusi1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnproses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nama);
        nama.setBounds(100, 30, 230, 30);
        getContentPane().add(nilai);
        nilai.setBounds(100, 150, 230, 30);
        getContentPane().add(absen);
        absen.setBounds(100, 70, 230, 30);
        getContentPane().add(mapel);
        mapel.setBounds(100, 110, 230, 30);

        jLabel1.setText("nilai");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 160, 50, 14);

        jLabel2.setText("penilain siswa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 90, 14);

        jLabel3.setText("absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 50, 14);

        jLabel4.setText("mapel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 50, 14);

        btnproses.setText("proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        getContentPane().add(btnproses);
        btnproses.setBounds(10, 250, 90, 23);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 190, 250, 100);

        jLabel5.setText("nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 40, 50, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
      String Nama = nama.getText();
        String Absen = absen.getText();
        String Mapel = mapel.getText();
        int Nilai = Integer.parseInt(nilai.getText());
        String hsl = "";
        if (Nilai < 75)
            hsl = "Tidak lulus";
        if (Nilai  >=75 && Nilai < 100)
            hsl = "Lulus";
        if (Nilai == 100)
            hsl = "Sempurna";
        if (Nilai > 100)
            hsl = "Amazing";
        
        hasil.setText("Nama             :"+Nama+"\n"+
                      "Absen            :"+Absen+"\n"+
                      "Mapel            :"     +Mapel+"\n"+
                      "Keterangan       :"  +hsl);  // TODO add your handling code here:
    }//GEN-LAST:event_btnprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kusi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kusi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kusi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kusi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kusi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JButton btnproses;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
