/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAFLI NUR FAUZI P
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan1
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        alamat = new javax.swing.JTextField();
        alamat1 = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        OKE = new javax.swing.JButton();
        Alamat = new java.awt.Label();
        nama = new java.awt.Label();
        kelas = new java.awt.Label();
        formulir = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Nama1 = new javax.swing.JTextField();
        Kelas1 = new javax.swing.JTextField();
        nama1 = new java.awt.Label();
        kelas1 = new java.awt.Label();
        Alamat1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(100, 110, 170, 30);
        getContentPane().add(alamat1);
        alamat1.setBounds(100, 270, 170, 30);
        getContentPane().add(Kelas);
        Kelas.setBounds(100, 70, 170, 30);

        OKE.setText("Proses");
        OKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKEActionPerformed(evt);
            }
        });
        getContentPane().add(OKE);
        OKE.setBounds(150, 150, 65, 23);

        Alamat.setText("Alamat");
        getContentPane().add(Alamat);
        Alamat.setBounds(40, 270, 42, 30);

        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(40, 190, 38, 30);

        kelas.setText("Kelas");
        getContentPane().add(kelas);
        kelas.setBounds(40, 230, 36, 30);

        formulir.setText("formulir");
        getContentPane().add(formulir);
        formulir.setBounds(160, 10, 50, 14);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(100, 30, 170, 30);
        getContentPane().add(Nama1);
        Nama1.setBounds(100, 190, 170, 30);
        getContentPane().add(Kelas1);
        Kelas1.setBounds(100, 230, 170, 30);

        nama1.setText("Nama");
        getContentPane().add(nama1);
        nama1.setBounds(40, 40, 38, 20);

        kelas1.setText("Kelas");
        getContentPane().add(kelas1);
        kelas1.setBounds(40, 70, 36, 20);

        Alamat1.setText("Alamat");
        getContentPane().add(Alamat1);
        Alamat1.setBounds(40, 110, 42, 20);

        setBounds(0, 0, 416, 376);
    }// </editor-fold>//GEN-END:initComponents

    private void OKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKEActionPerformed
       String nama = Nama.getText();
       Nama1.setText(nama);
       String kelas = Kelas.getText();
       Kelas1.setText(kelas);
       String Alamat = alamat.getText();
       alamat1.setText(Alamat); 
       
       
        // TODO add your handling code here:
    }//GEN-LAST:event_OKEActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Alamat;
    private java.awt.Label Alamat1;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Kelas1;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nama1;
    private javax.swing.JButton OKE;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField alamat1;
    private javax.swing.JLabel formulir;
    private java.awt.Label kelas;
    private java.awt.Label kelas1;
    private java.awt.Label nama;
    private java.awt.Label nama1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
